language: node_js
node_js:
- 0.12
- 4
- node
script: npm run test:ci
notifications:
  email: false
  slack:
    secure: Xh14Pjz9ZwN7xXdAGw+639uhdjFyKIbb7MYFU9ckyi97HIS3ROD9M+FsD4F/KpZ6wMLSltvU8F873bi1KwiWp5jJtG5DJdAgaMV1vluZiuD8Bk1tArBAH/A4wS/11v0i+oYPtnbYq3udg9vaSwD9PlKle8+BZEGryVhzMrwBzy8=
